In [1]:
#Problem 1: Array Creation
import numpy as np

# 1. Initialize an empty array with size 2x2.
empty_array = np.empty((2, 2))
print("Empty Array:\n", empty_array)

# 2. Initialize an all-ones array with size 4x2.
ones_array = np.ones((4, 2))
print("\nAll-Ones Array:\n", ones_array)

# 3. Return a new array of given shape and type, filled with a fill value.
fill_array = np.full((3, 3), 7)  # Example fill value = 7
print("\nFilled Array with 7:\n", fill_array)

# 4. Return a new array of zeros with the same shape and type as a given array.
given_array = np.array([[2, 3], [5, 6]])
zeros_like_array = np.zeros_like(given_array)
print("\nZeros-Like Array:\n", zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array.
ones_like_array = np.ones_like(given_array)
print("\nOnes-Like Array:\n", ones_like_array)

# 6. Convert an existing list to a numpy array.
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nNumpy Array from List:\n", numpy_array)


Empty Array:
 [[0. 0.]
 [0. 0.]]

All-Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Filled Array with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros-Like Array:
 [[0 0]
 [0 0]]

Ones-Like Array:
 [[1 1]
 [1 1]]

Numpy Array from List:
 [1 2 3 4]


In [2]:
#Problem 2: Array Manipulation
# 1. Create an array with values ranging from 10 to 49.
array_range = np.arange(10, 50)
print("\nArray from 10 to 49:\n", array_range)

# 2. Create a 3x3 matrix with values ranging from 0 to 8.
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix:\n", matrix_3x3)

# 3. Create a 3x3 identity matrix.
identity_matrix = np.eye(3)
print("\nIdentity Matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find its mean.
random_array = np.random.random(30)
array_mean = random_array.mean()
print("\nMean of Random Array:\n", array_mean)

# 5. Create a 10x10 array with random values and find the minimum and maximum values.
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 Random Array:\n", random_10x10)
print("Min Value:", min_value, "Max Value:", max_value)

# 6. Create a zero array of size 10 and replace the 5th element with 1.
zero_array = np.zeros(10)
zero_array[4] = 1  # Index 4 is the 5th element
print("\nZero Array with 5th Element as 1:\n", zero_array)

# 7. Reverse an array.
arr = [1, 2, 0, 0, 4, 0]
reversed_array = np.array(arr)[::-1]
print("\nReversed Array:\n", reversed_array)

# 8. Create a 2D array with 1 on the border and 0 inside.
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with Border:\n", border_array)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern.
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\nCheckerboard Pattern:\n", checkerboard)



Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Mean of Random Array:
 0.6379442458584778

10x10 Random Array:
 [[0.76280514 0.26213973 0.95227833 0.52920622 0.38607896 0.67770248
  0.1664518  0.9773557  0.27704567 0.3135132 ]
 [0.61587199 0.11283111 0.40264039 0.26344643 0.87251362 0.17018694
  0.54403992 0.76099022 0.11560503 0.79613973]
 [0.18930524 0.13657272 0.48190667 0.21213999 0.7168609  0.78926345
  0.78571309 0.7000999  0.98920465 0.30046059]
 [0.14876447 0.59028675 0.95608389 0.81812192 0.11086222 0.98256867
  0.35867579 0.92479524 0.77444968 0.00756874]
 [0.35793747 0.13462787 0.723854   0.78402033 0.50971917 0.23586518
  0.9304458  0.04708714 0.92097815 0.98906104]
 [0.52954411 0.02472933 0.7058417  0.53635568 0.21323463 0.71886076
  0.41232341 0.87912216 0.62555102 0.53610683]
 

In [3]:
#Problem 3: Array Operations
# Define arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays.
add_result = x + y
print("\nAddition:\n", add_result)

# 2. Subtract the two arrays.
subtract_result = x - y
print("\nSubtraction:\n", subtract_result)

# 3. Multiply the array with an integer.
multiplied = x * 3
print("\nArray Multiplied by 3:\n", multiplied)

# 4. Find the square of each element.
square_result = x ** 2
print("\nElement-wise Square:\n", square_result)

# 5. Dot products
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\nDot Products:\n v.w =", dot_vw, "\n x.v =\n", dot_xv, "\n x.y =\n", dot_xy)

# 6. Concatenate along rows and columns.
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.vstack((v, w))
print("\nConcatenate x and y (row):\n", concat_xy_row)
print("\nConcatenate v and w (column):\n", concat_vw_col)

# 7. Concatenate x and v (Observe Error)
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    print("\nError when concatenating x and v:\n", e)



Addition:
 [[ 6  8]
 [10 13]]

Subtraction:
 [[-4 -4]
 [-4 -3]]

Array Multiplied by 3:
 [[ 3  6]
 [ 9 15]]

Element-wise Square:
 [[ 1  4]
 [ 9 25]]

Dot Products:
 v.w = 219 
 x.v =
 [29 77] 
 x.y =
 [[19 22]
 [50 58]]

Concatenate x and y (row):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w (column):
 [[ 9 10]
 [11 12]]

Error when concatenating x and v:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [4]:
#Problem 4: Matrix Operations
# Define matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A^(-1) = I
A_inv = np.linalg.inv(A)
result_identity = np.dot(A, A_inv)
print("\nA * A^(-1) = I:\n", result_identity)

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("\nBA:\n", BA)

# 3. Prove (AB)^T = B^T A^T
AB_T = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)
print("\n(AB)^T:\n", AB_T)
print("\nB^T A^T:\n", BT_AT)

# Solve Linear Equations
coeff_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
constants = np.array([-1, -3, 9])

# Solve using Inverse
solution = np.dot(np.linalg.inv(coeff_matrix), constants)
print("\nSolution using Inverse Method:\n", solution)



A * A^(-1) = I:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

(AB)^T:
 [[23 51]
 [13 29]]

B^T A^T:
 [[23 51]
 [13 29]]

Solution using Inverse Method:
 [ 2.  1. -2.]
